matrix:
    include:
    

-language: java

    services:
      - docker
      - maven

    script:

      # Copy new generated resources on back static
      - cd ../backend
      - mkdir -p "src/main/resources/static/" && cp -r ../frontend/dist/my-app/* src/main/resources/static/

      # Create jar
      - mvn package 
      
-language: node_js
     node_js: 10.9
     
     script:
            # Build frontend
              - cd frontend
              - npm install
              - npm run build

              # Run front tests
              - npm run test-ci